version: "3.8"

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"

    env_file:
      - .env
    volumes:
      - .:/app
    command: air

  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
